"""brief.py -- a provider-neutral resume brief, fitted to a target's budget.

`make_brief` turns a project's pool into the text a new agent reads first:
focus, open work, recent decisions with their rejected alternatives, and
constraints. The brief is a strict prefix of that priority order: when the
budget runs out, everything after the cut is left out whole, and the brief ends
with a "Left out" section naming what was cut. Nothing lower in the order is
shown while something higher is missing.

The receipt (`canon.handoff-receipt/v1`) records the budget, the brief's digest,
a digest of the pool it was built from, every included and left-out record with
its content hash, every record excluded by rule and why, and the projects the
caller declared. No clock is read, so the same pool gives the same bytes.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, replace

from canon.versions import PIN_HANDOFF_RECEIPT
from canon.workspace.brief_items import (
    NO_FILE_REASON,
    SECTIONS,
    BriefItem,
    Exclusion,
    collect,
    one_line,
)
from canon.workspace.identity import ProjectIdentity
from canon.workspace.pool import TaggedRecord
from canon.workspace.scrub import find_secrets
from canon.workspace.target_fidelity import (
    DECLARED_DOWNGRADES,
    IMPORT_HOSTS,
    OMITTED,
    quote_at_imports,
)
from canon.workspace.targets import Target

RECEIPT_SCHEMA = PIN_HANDOFF_RECEIPT.kind_tag
DOES_NOT_PROVE = (
    "The brief shows accepted records of this project, global records and any "
    "declared project. It does not show proposed records or anything that was "
    "never recorded.",
    "A record in the brief is what someone recorded. It does not prove the code "
    "still matches it.",
    "The budget is canon's default for the target, not a measured limit of what "
    "the target model attends to.",
)


class BudgetError(ValueError):
    """The budget cannot hold even the brief's header."""


class SecretInRender(ValueError):
    """Rendered text still carries a secret-shaped value. The store refuses one
    on write, so this fires only for a store file edited by hand."""


def refuse_secrets(text: str, what: str) -> None:
    leaked = find_secrets(text)
    if leaked:
        raise SecretInRender(f"the {what} would carry secret-shaped values {leaked}; "
                             "nothing was written")


@dataclass(frozen=True, slots=True)
class Brief:
    text: str
    receipt: dict
    included: tuple[BriefItem, ...]
    left_out: tuple[BriefItem, ...]


@dataclass(frozen=True, slots=True)
class _Budget:
    """A budget for the text as it lands: `overhead` is what the caller adds
    around the brief (a sentinel line when it becomes a region block)."""

    bytes: int
    lines: int
    overhead: tuple[int, int] = (0, 0)

    def fits(self, text: str) -> bool:
        return (len(text.encode("utf-8")) + self.overhead[0] <= self.bytes
                and text.count("\n") + self.overhead[1] <= self.lines)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _header(identity: ProjectIdentity, target: Target, level: int) -> list[str]:
    title = f"{'#' * level} Resume brief: {one_line(identity.label)}"
    return [title, "",
            f"Project {identity.project_id} ({identity.method} {identity.key}), "
            f"written for {target.display}.",
            "Generated by canon from recorded project state. It holds what was "
            "recorded, not everything that happened in earlier sessions."]


def _sections(included: list[BriefItem], every: list[BriefItem], level: int) -> list[str]:
    lines: list[str] = []
    for section in SECTIONS:
        shown = [i for i in included if i.section == section]
        exists = any(i.section == section for i in every)
        if not shown and exists:
            continue
        lines += ["", f"{'#' * (level + 1)} {section}"]
        lines += [line for i in shown for line in i.lines] or ["None recorded."]
    return lines


def _footer(rest: list[BriefItem], target: Target, budget: _Budget,
            used: str, level: int, hint: str) -> list[str] | None:
    head = ["", f"{'#' * (level + 1)} Left out",
            f"{len(rest)} records did not fit the {target.display} budget "
            f"({budget.bytes} bytes, {budget.lines} lines). {hint}"]
    if not budget.fits(used + "\n".join(head) + "\n"):
        return None
    listed: list[str] = []
    for index, item in enumerate(rest):
        line = f"- {item.record.kind} {item.record.id}: {one_line(_label(item))}"
        more = [] if index == len(rest) - 1 else [f"- and {len(rest) - index - 1} more"]
        if not budget.fits(used + "\n".join(head + listed + [line] + more) + "\n"):
            break
        listed.append(line)
    if len(listed) < len(rest):
        listed.append(f"- and {len(rest) - len(listed)} more")
    return head + listed


def _label(item: BriefItem) -> str:
    data = item.record.data
    return str(data.get("title") or data.get("goal") or data.get("statement")
               or item.record.id)


def _largest_fitting_prefix(body, total: int, budget: _Budget) -> int:
    """Binary search for the longest prefix whose body alone fits. The body
    only grows as items are added, so the search is exact."""
    lo, hi = 0, total
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if budget.fits(body(mid)):
            lo = mid
        else:
            hi = mid - 1
    return lo


def _assemble(header: list[str], items: list[BriefItem], target: Target,
              budget: _Budget, level: int, hint: str) -> tuple[int, str]:
    def body(n: int) -> str:
        return "\n".join(header + _sections(items[:n], items, level)) + "\n"

    whole = body(len(items))
    if budget.fits(whole):
        return len(items), whole
    start = _largest_fitting_prefix(body, len(items), budget)
    for n in range(min(start, len(items) - 1), -1, -1):
        text = body(n)
        footer = _footer(items[n:], target, budget, text, level, hint)
        if footer is not None:
            text += "\n".join(footer) + "\n"
            if budget.fits(text):
                return n, text
    raise BudgetError(
        f"a budget of {budget.bytes} bytes and {budget.lines} lines cannot hold "
        "the brief header and its truncation report")


def _hint(target: Target, receipt_hint: str | None) -> str:
    return receipt_hint or (f"Run canon handoff --to {target.name} --receipt FILE to "
                            "list every one.")


def make_brief(identity: ProjectIdentity, pool: list[TaggedRecord], target: Target, *,
               budget_bytes: int | None = None, budget_lines: int | None = None,
               declared: tuple[str, ...] = (), level: int = 1,
               overhead: tuple[int, int] = (0, 0), receipt_hint: str | None = None) -> Brief:
    """The brief for `target`, fitted to its budget (or the override), and its
    receipt. `level` is the heading depth of the title (1 standalone, 2 inside
    an instruction region); `overhead` is what the caller adds around the text
    as it lands; `receipt_hint` is the sentence that says where the full list
    of left-out records is. On a host that reads `@path` as an import, every
    such token in a record line is quoted so it stays text."""
    budget = _Budget(target.brief_bytes if budget_bytes is None else budget_bytes,
                     target.brief_lines if budget_lines is None else budget_lines, overhead)
    if budget.bytes < 1 or budget.lines < 1:
        raise BudgetError("a budget must be at least one byte and one line")
    items, excluded = collect(pool, identity.project_id, has_file=target.harness is not None)
    if target.name in IMPORT_HOSTS:
        items = [replace(i, lines=tuple(quote_at_imports(line) for line in i.lines))
                 for i in items]
    n, text = _assemble(_header(identity, target, level), items, target, budget, level,
                        _hint(target, receipt_hint))
    refuse_secrets(text, "brief")
    included, left_out = tuple(items[:n]), tuple(items[n:])
    receipt = _receipt(identity, pool, target, budget, text, included, left_out,
                       excluded, declared)
    refuse_secrets(json.dumps(receipt, ensure_ascii=False), "brief receipt")
    return Brief(text, receipt, included, left_out)


def omitted_blocks(brief: Brief) -> dict:
    """The instruction blocks a target with no instruction file cannot carry:
    how many, their ids, and why (None when there are none)."""
    ids = [e["id"] for e in brief.receipt["excluded"] if e["reason"] == NO_FILE_REASON]
    target = brief.receipt["target"]["name"]
    reason = DECLARED_DOWNGRADES.get(target, {}).get(OMITTED) if ids else None
    return {"count": len(ids), "ids": ids, "reason": reason}


def omitted_note(omitted: dict) -> str | None:
    """One line saying what `omitted_blocks` found, or None."""
    count = omitted["count"]
    if not count:
        return None
    return f"{count} instruction block{'' if count == 1 else 's'} omitted: {omitted['reason']}"


def _ref(project_id: str | None, record) -> dict:
    return {"project_id": project_id, "kind": record.kind, "id": record.id,
            "record_sha256": _sha256(record.to_json())}


def pool_digest(pool: list[TaggedRecord]) -> str:
    rows = sorted(([t.project_id or "", t.record.to_dict()] for t in pool),
                  key=lambda r: (r[0], r[1]["scope"], r[1]["id"]))
    return _sha256(json.dumps(rows, sort_keys=True, ensure_ascii=False))


def _receipt(identity, pool, target, budget, text, included, left_out,
             excluded: list[Exclusion], declared) -> dict:
    return {
        "schema": RECEIPT_SCHEMA,
        "project": identity.to_public(),
        "target": {"name": target.name, "budget_bytes": budget.bytes,
                   "budget_lines": budget.lines, "basis": target.basis},
        "brief": {"sha256": _sha256(text), "bytes": len(text.encode("utf-8")),
                  "lines": text.count("\n")},
        "pool_sha256": pool_digest(pool),
        "declared_projects": sorted(declared),
        "included": [_ref(i.project_id, i.record) for i in included],
        "left_out": [{**_ref(i.project_id, i.record), "reason": "budget",
                      "label": one_line(_label(i))} for i in left_out],
        "excluded": [{"project_id": e.project_id, "kind": e.kind, "id": e.id,
                      "reason": e.reason} for e in excluded],
        "does_not_prove": list(DOES_NOT_PROVE),
    }
