"""canon -- a provider-neutral memory-bank + personality container.

F0 ships the record of record: one canonical envelope (schema.py), its
semantic validator (validator.py), and the per-scope override layering that
resolves the canon block set for a render target (layering.py). F1 adds the
storage seam (backends/): the MemoryBackend Protocol and its four adapters,
each declaring what a round-trip through it drops. Renderers, verifiers, and
migration legs are later phases; they all aim at the envelope this package
defines.
"""
from __future__ import annotations

from .adapter import (
    ADAPTER_SCHEMA,
    AdapterDescriptor,
    assert_requested_tier_allowed,
    builtin_descriptors,
    descriptor_for,
    validate_adapter_descriptor,
)
from .atom import (
    ATOM_SCHEMA,
    CanonAtom,
    atom_key,
    atoms_from_records,
    is_valid_atom,
    load_atoms_jsonl,
    validate_atom,
)
from .backends import (
    CAP_ARBITRARY_KIND,
    CAP_AUDIT_CHAIN,
    CAP_FOREIGN_PROVENANCE,
    CAP_RELATIONS,
    CAP_TEMPORAL,
    BackendError,
    DropError,
    FilesBackend,
    FlywheelBackend,
    InvalidKey,
    InvalidRecord,
    MemoryBackend,
    MnemeBackend,
    SqliteBackend,
    UnsupportedKind,
    capabilities_required,
    guard_put,
    record_key,
    validate_put_record,
)
from .canonical_json import (
    CanonicalJSONError,
    canonical_json_bytes,
    canonical_json_text,
    canonical_sha256,
    is_sha256_ref,
    sha256_bytes,
    sha256_text,
)
from .capsule import (
    CAPSULE_SCHEMA,
    Budget,
    Capsule,
    CapsuleBundle,
    CapsuleCompileRequest,
    CapsuleTarget,
    Compatibility,
    Integrity,
    SourceState,
    build_capsule,
    capsule_bytes,
    capsule_digest,
    compile_capsule,
    validate_capsule,
)
from .canonmd import (
    CANON_MD_SECTIONS,
    parse_canon_md_carrier,
    render_canon_md,
    verify_canon_md,
)
from .layering import LayeringError, is_current, resolve_blocks
from .omission import OMISSION_SCHEMA, Omission, validate_omission
from .readiness import (
    READINESS_PROBE_SCHEMA,
    READINESS_RESULT_SCHEMA,
    ReadinessProbe,
    ReadinessResult,
    evaluate_readiness_response,
    validate_readiness_probe,
    validate_readiness_result,
)
from .schema import (
    ADR_STATUSES,
    EPISODIC_LAYERS,
    KIND_ADR_DECISION,
    KIND_EPISODIC_MEMORY,
    KIND_PERSONALITY_BLOCK,
    KIND_RESEARCH_ARTIFACT_REF,
    KIND_SYNTHESIZED_PERSONA_L3,
    KINDS,
    PERSONA_LAYER,
    SCHEMA,
    SCOPE_GLOBAL,
    SCOPE_WORKSPACE,
    SCOPES,
    TEMPORAL_KINDS,
    Provenance,
    Record,
    Temporal,
    is_sha256,
)
from .transform import TRANSFORM_SCHEMA, TransformReceipt, validate_transform_receipt
from .validator import is_valid, validate_record
from .witness import (
    BOOTSTRAP_WITNESS_SCHEMA,
    BootstrapCheck,
    BootstrapWitness,
    validate_bootstrap_witness,
)

__all__ = [
    "SCHEMA",
    "KINDS",
    "KIND_PERSONALITY_BLOCK",
    "KIND_EPISODIC_MEMORY",
    "KIND_SYNTHESIZED_PERSONA_L3",
    "KIND_ADR_DECISION",
    "KIND_RESEARCH_ARTIFACT_REF",
    "TEMPORAL_KINDS",
    "SCOPES",
    "SCOPE_GLOBAL",
    "SCOPE_WORKSPACE",
    "EPISODIC_LAYERS",
    "PERSONA_LAYER",
    "ADR_STATUSES",
    "Record",
    "Provenance",
    "Temporal",
    "is_sha256",
    "validate_record",
    "is_valid",
    "resolve_blocks",
    "is_current",
    "LayeringError",
    "MemoryBackend",
    "BackendError",
    "InvalidRecord",
    "InvalidKey",
    "UnsupportedKind",
    "DropError",
    "FilesBackend",
    "SqliteBackend",
    "MnemeBackend",
    "FlywheelBackend",
    "CAP_TEMPORAL",
    "CAP_AUDIT_CHAIN",
    "CAP_RELATIONS",
    "CAP_ARBITRARY_KIND",
    "CAP_FOREIGN_PROVENANCE",
    "record_key",
    "capabilities_required",
    "guard_put",
    "validate_put_record",
    "canonical_json_text",
    "canonical_json_bytes",
    "sha256_bytes",
    "sha256_text",
    "canonical_sha256",
    "is_sha256_ref",
    "CanonicalJSONError",
    "ATOM_SCHEMA",
    "CanonAtom",
    "atom_key",
    "atoms_from_records",
    "load_atoms_jsonl",
    "validate_atom",
    "is_valid_atom",
    "OMISSION_SCHEMA",
    "Omission",
    "validate_omission",
    "TRANSFORM_SCHEMA",
    "TransformReceipt",
    "validate_transform_receipt",
    "ADAPTER_SCHEMA",
    "AdapterDescriptor",
    "builtin_descriptors",
    "descriptor_for",
    "assert_requested_tier_allowed",
    "validate_adapter_descriptor",
    "READINESS_PROBE_SCHEMA",
    "READINESS_RESULT_SCHEMA",
    "ReadinessProbe",
    "ReadinessResult",
    "evaluate_readiness_response",
    "validate_readiness_probe",
    "validate_readiness_result",
    "BOOTSTRAP_WITNESS_SCHEMA",
    "BootstrapCheck",
    "BootstrapWitness",
    "validate_bootstrap_witness",
    "CAPSULE_SCHEMA",
    "Capsule",
    "CapsuleTarget",
    "SourceState",
    "Compatibility",
    "Budget",
    "Integrity",
    "CapsuleCompileRequest",
    "CapsuleBundle",
    "build_capsule",
    "compile_capsule",
    "capsule_bytes",
    "capsule_digest",
    "validate_capsule",
    "CANON_MD_SECTIONS",
    "render_canon_md",
    "parse_canon_md_carrier",
    "verify_canon_md",
]
